[package]
name = "apex-hardware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
usb = ["dep:apex-hidapi-static"]
experimental-openrgb-support = ["dep:apex-hidapi-default"]
async = []

[dependencies]
anyhow = "1.0.44"
apex-hidapi-default = { path = "../apex-hidapi-default", optional = true }
apex-hidapi-static = { path = "../apex-hidapi-static", optional = true }
bitvec = "1.0.1"
embedded-graphics = "0.8"
num_enum = "0.5.4"
